# Generated by Django 4.2.23 on 2025-06-19 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
    ]
